# Generated by Django 4.2.6 on 2023-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=15)),
                ("contraseña", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=20)),
                ("fnac", models.DateField()),
                ("mail", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "producto", "verbose_name_plural": "productos"},
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="foto4",
            new_name="foto3",
        ),
    ]
