# Generated by Django 4.2.7 on 2023-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='create',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='update',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fnac',
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto2',
            field=models.ImageField(default=None, null=True, upload_to='valioso_Mapp'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto3',
            field=models.ImageField(default=None, null=True, upload_to='valioso_Mapp'),
        ),
    ]
