# Generated by Django 4.2.6 on 2023-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_usuario_alter_producto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="usuario_prod",
            field=models.CharField(default="Nombre de usuario", max_length=15),
        ),
    ]
