# Generated by Django 4.2.7 on 2023-11-27 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_create_remove_producto_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fnac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
