# Generated by Django 4.2.6 on 2023-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_usuario_alter_producto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD:valioso_Mapp/migrations/0003_producto_usuario_prod.py
            model_name='producto',
            name='usuario_prod',
            field=models.ForeignKey(to='valioso_Mapp.usuario', on_delete=models.CASCADE),
=======
            model_name="producto",
            name="usuario_prod",
            field=models.CharField(default="Nombre de usuario", max_length=15),
>>>>>>> 0fb9d7a0d9bbb6bab061937fb0f6c43599de89c4:core/migrations/0003_producto_usuario_prod.py
        ),
    ]
