# Generated by Django 4.2.7 on 2023-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valioso_Mapp', '0003_producto_usuario_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(help_text='Ingrese una descripcion del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuario_prod',
            field=models.CharField(default='Nombre de usuario', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
