# Generated by Django 4.2.7 on 2023-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
