# Generated by Django 4.2.6 on 2023-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese un Título para producto ', max_length=50)),
                ('descripcion', models.CharField(help_text='Ingrese una descripcion del producto', max_length=200)),
                ('foto1', models.ImageField(upload_to='valioso_Mapp')),
                ('foto2', models.ImageField(upload_to='valioso_Mapp')),
                ('foto4', models.ImageField(upload_to='valioso_Mapp')),
                ('create', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
