# Generated by Django 4.2.6 on 2023-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valioso_Mapp', '0002_usuario_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario_prod',
            field=models.ForeignKey(to='valioso_Mapp.usuario', on_delete=models.CASCADE),
        ),
    ]
